// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerLib.Model;

#nullable disable

namespace ServerLib.Migrations
{
    [DbContext(typeof(SDDatabase))]
    partial class SDDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ServerLib.Model.AccountDb", b =>
                {
                    b.Property<int>("DbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PlayerNickname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DbId");

                    b.ToTable("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
